apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: icgroup
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: odoo@gmail.com
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: icgroup-secret
              key: progres_password

# Service configuration because every application needs a service
---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: icgroup
spec:
  type: NodePort
  selector:
    # same name of pod, it needs to match in order the service to select the good pod
    app: pgadmin
  ports:
    - protocol: TCP
      # Service port, it common to use the targetPort as service port
      port: 80
      # Container port inside Pod, the service forwards the request to targetPort
      targetPort: 80
      # nodePort exposes the service on each Node's IP at static port range: 30000-32767 
      nodePort: 30100

