apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdd-odoo-deployment
  namespace: icgroup
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdd-odoo
  template:
    metadata:
      labels:
        app: bdd-odoo
    spec:
      containers:
      - name: postgres
        image: postgres:13
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-data
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: icgroup-secret
              key: progres_password
      volumes:
      - name: postgresql-data
      # chemin du dossier sur l'hote
        hostPath:
          path: /data/postgresql
      # ce champ est optionel
          type: Directory

# Service configuration because every application needs a service
---

apiVersion: v1
kind: Service
metadata:
  name: bdd-odoo-service
  namespace: icgroup
  labels:
    env: prod
spec:
  selector:
    # same name of pod, it needs to match in order the service to select the good pod
    app: bdd-odoo
  ports:
    - protocol: TCP
      # Service port, it common to use the targetPort as service port
      port: 5432
      # Container port inside Pod, the service forwards the request to targetPort
      targetPort: 5432

