apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-web-deployment
  namespace: icgroup
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-web
  template:
    metadata:
      labels:
        app: odoo-web
    spec:
      containers:
      - name: odoo-web
        image: odoo:latest
        volumeMounts:
        - mountPath: /var/lib/lib/odoo
          name: odoo-data
        ports:
        - containerPort: 8069
        env:
        - name: HOST
          value: bdd-odoo-service
        - name: USER
          value: odoo
        - name: POSTGRES_DB
          value: postgres
        - name: PASSWORD
          valueFrom: 
            secretKeyRef:
              name: icgroup-secret
              key: progres_password
      volumes:
      - name: odoo-data
      # chemin du dossier sur l'hote
        hostPath:
          path: /data/odoo
      # ce champ est optionel
          type: Directory
   

# Service configuration because every application needs a service
---

apiVersion: v1
kind: Service
metadata:
  name: odoo-web-service
  namespace: icgroup
  labels:
    env: prod
spec:
  type: NodePort
  selector:
    # same name of pod, it needs to match in order the service to select the good pod
    app: odoo-web
  ports:
    - protocol: TCP
      # Service port, it common to use the targetPort as service port
      port: 8069
      # Container port inside Pod, the service forwards the request to targetPort
      targetPort: 8069
      # nodePort exposes the service on each Node's IP at static port range: 30000-32767 
      nodePort: 30300
